# agents/claim_submitter.py - Enhanced with MCP Integration

import httpx
import asyncio
import random
from config.settings import Settings
from tools.logger import secure_log
from tools.csv_data_loader import patient_loader
from orchestrator.mcp_client import mcp_client
from datetime import datetime
from tools.denial_reasons import DenialReasonGenerator

# Import centralized execution logger
try:
    from tools.execution_logger import execution_logger, log_execution, log_error
    HAS_EXECUTION_LOGGER = True
except ImportError:
    HAS_EXECUTION_LOGGER = False

from tools.denial_reasons import DenialReasonGenerator

def generate_mock_submission_result(claim_id: str, insurance_company: str, claim_data: dict = None) -> dict:
    """Generate realistic mock response based on actual claim data quality with specific denial reasons"""
    
    denial_generator = DenialReasonGenerator()
    
    if claim_data:
        patient_name = claim_data.get("patient_name", "Unknown Patient")
        claim_amount = claim_data.get("claim_amount", 0)
        
        # Calculate data quality score
        quality_score = 0.0
        if claim_data.get("prior_auth"):
            quality_score += 0.3
        if claim_data.get("medical_history"):
            quality_score += 0.3
        if all(claim_data.get(field) for field in ["age", "gender", "date_of_birth"]):
            quality_score += 0.4
            
        # Determine if claim should be denied
        should_deny = quality_score < 0.7 or random.random() < 0.5  # Deny if quality low or 50% random for testing
        
        # Force denial for testing high amounts or invalid codes
        if claim_amount > 10000 or claim_data.get("cpt_code") == "99999":
            should_deny = True
        
        if should_deny:
            denial_info = denial_generator.get_specific_denial(insurance_company, claim_amount)
            
            # Format the denial message with specific details
            current_time = datetime.now().strftime("%m/%d/%Y, %I:%M:%S %p")
            denial_message = (
                f"{patient_name} REJECTED\n"
                f"Claim Amount: ${claim_amount}\n"
                f"Insurer: {insurance_company}\n"
                f"Rejected: {current_time}\n\n"
                f"Reason: {denial_info['reason']}\n"
                f"Details: {denial_info['details']}\n\n"
                f"Required for Resubmission:\n"
            )
            for item in denial_info.get('required_items', []):
                denial_message += f"- {item}\n"
            success_rate = denial_info.get('success_rate', 0.75) * 100  # Default 75% if missing
            denial_message += f"\nEstimated approval rate after providing required items: {success_rate}%"
            
            return {
                "status": "rejected",
                "claim_id": claim_id,
                "message": denial_message,
                "denial_info": denial_info,
                "data_quality_score": round(quality_score * 100, 1)
            }
        else:
            # Approve the claim
            approved_amount = claim_amount * random.uniform(0.85, 1.0)
            return {
                "status": "approved",
                "claim_id": claim_id,
                "approved_amount": round(approved_amount, 2),
                "data_quality_score": round(quality_score * 100, 1)
            }
    
    # Default behavior for missing claim data
    if random.random() < 0.3:  # 30% denial rate
        denial_info = denial_generator.get_specific_denial(insurance_company, 0)
        return {
            "status": "rejected",
            "claim_id": claim_id,
            "message": "Insufficient claim data provided",
            "denial_info": denial_info,
            "data_quality_score": 0.0
        }
    
    return {
        "status": "approved",
        "claim_id": claim_id,
        "approved_amount": random.uniform(500, 3000),
        "data_quality_score": 50.0  # Default score for missing data
    }
    
    if is_approved:
        # Approved claim with realistic amount
        approval_amount = actual_amount * random.uniform(0.85, 1.0)  # 85-100% of claim
        
        return {
            "status": "approved",
            "claim_id": claim_id,
            "reason": "Claim approved after data quality verification",
            "approval_amount": round(approval_amount, 2),
            "approved_amount": round(approval_amount, 2),  # Add both for compatibility
            "processed_by": f"Mock_{insurance_company}_API",
            "processing_time": "Instant (Mock)",
            "data_quality_score": round(approval_rate * 100, 1),
            "notes": "Generated by intelligent mock system - approval based on data completeness"
        }
    else:
        # Denied claim with specific reasons based on missing data
        denial_reasons = []
        
        if claim_data:
            if not claim_data.get("prior_auth"):
                denial_reasons.append("Prior authorization required")
            if not claim_data.get("medical_history") or claim_data.get("medical_history") == "None":
                denial_reasons.append("Insufficient medical documentation")
            if not all(claim_data.get(field) for field in ["patient_name", "age", "gender"]):
                denial_reasons.append("Incomplete patient demographics")
            if claim_data.get("claim_amount", 0) > 500:
                denial_reasons.append("Amount exceeds typical range for procedure")
        
        if not denial_reasons:
            denial_reasons = ["Service not covered under current policy"]
        
        return {
            "status": "denied",
            "claim_id": claim_id,
            "reason": "; ".join(denial_reasons),
            "processed_by": f"Mock_{insurance_company}_API",
            "processing_time": "Instant (Mock)",
            "data_quality_score": round(approval_rate * 100, 1),
            "notes": "Generated by intelligent mock system - denial based on data quality issues"
        }

async def run_claim_submission(state: dict) -> dict:
    """Enhanced Claim Submitter Agent with MCP integration and detailed stage output"""
    
    claim_payload = state.get("corrected_data") or state.get("raw_data")
    claim_id = state.get("claim_id", "unknown")
    patient_name = claim_payload.get("patient_name", "Unknown Patient")
    insurance_company = claim_payload.get("insurance_company", "")
    patient_id = claim_payload.get("patient_id", "")
    remaining_issues = state.get("issues", [])
    
    # Log agent start with centralized logger
    if HAS_EXECUTION_LOGGER:
        log_execution('claim_submitter', 'AGENT_START', {
            'claim_id': claim_id,
            'patient_name': patient_name,
            'insurance_company': insurance_company,
            'claim_amount': claim_payload.get('claim_amount', 0),
            'remaining_issues': len(remaining_issues),
            'action': 'Starting intelligent claim submission with real-time eligibility verification'
        })
    
    print("\n" + "="*80)
    print("� STAGE 3: INTELLIGENT CLAIM SUBMISSION")
    print("="*80)
    
    print(f"�📋 Processing Claim: {claim_id}")
    print(f"   Patient: {patient_name}")
    print(f"   Patient ID: {patient_id}")
    print(f"   Insurance: {insurance_company}")
    print(f"   Remaining issues: {len(remaining_issues)}")
    print(f"   Claim amount: ${claim_payload.get('claim_amount', 0)}")
    
    if remaining_issues:
        print(f"\n   ⚠️  Outstanding Issues:")
        for issue in remaining_issues:
            print(f"      • {issue}")
    
    print(f"\n🔗 PRE-SUBMISSION VERIFICATION:")
    
    # Add detailed logging for UI activity tracking
    state["log"].append("[ClaimSubmitter] Real-time eligibility verification with insurance provider")
    state["log"].append("[ClaimSubmitter] Routes based on insurer: BlueCross/Aetna → Primary API (8081), Cigna/United → Secondary API (8082)")
    
    # Log eligibility verification
    if HAS_EXECUTION_LOGGER:
        log_execution('claim_submitter', 'ELIGIBILITY_CHECK', {
            'claim_id': claim_id,
            'patient_name': patient_name,
            'insurance_company': insurance_company,
            'action': 'Performing real-time eligibility verification via MCP'
        })
    
    # Perform real-time eligibility check via MCP before submission
    try:
        print(f"   🔍 Checking patient eligibility...")
        state["log"].append("[ClaimSubmitter] Checking patient eligibility via MCP real-time check")
        
        eligibility_result = await mcp_client.real_time_eligibility_check(
            patient_id=patient_id,
            service_date=datetime.now().strftime("%Y-%m-%d")
        )
        
        if eligibility_result.get("eligible", False):
            print(f"   ✅ Patient eligible for coverage")
            print(f"      Coverage type: {eligibility_result.get('coverage_type', 'Standard')}")
            print(f"      Effective date: {eligibility_result.get('effective_date', 'Current')}")
        else:
            print(f"   ❌ Patient not eligible")
            print(f"      Reason: {eligibility_result.get('reason', 'Unknown')}")
            
            result = {
                "status": "denied",
                "reason": f"Eligibility check failed: {eligibility_result.get('reason', 'Not eligible')}",
                "eligibility_details": eligibility_result,
                "claim_id": claim_id,
                "timestamp": datetime.now().isoformat()
            }
            
            state["log"].append(f"[ClaimSubmitter-MCP] Eligibility check failed: {result['reason']}")
            state["submission_result"] = result
            state["final_status"] = "denied"
            
            print(f"\n📊 SUBMISSION FAILED:")
            print(f"   Status: DENIED")
            print(f"   Reason: Eligibility failure")
            print("="*80)
            return state
        
        # Log successful eligibility check
        state["log"].append(f"[ClaimSubmitter-MCP] Eligibility verified")
        
    except Exception as e:
        print(f"   ⚠️  Eligibility check error: {str(e)}")
        state["log"].append(f"[ClaimSubmitter-MCP] Eligibility check error: {str(e)}")
        # Continue with submission but log the issue
    
    # Validate CSV data match
    print(f"\n📊 CSV DATA VALIDATION:")
    patient_csv_data = patient_loader.get_patient_by_id(patient_id)
    
    if patient_csv_data:
        print(f"   ✅ Patient data validated against CSV")
        csv_insurance = patient_csv_data.get('insurer', '').lower()
        claim_insurance = insurance_company.lower()
        
        if csv_insurance == claim_insurance:
            print(f"   ✅ Insurance match: {insurance_company}")
        else:
            print(f"   ⚠️  Insurance mismatch: claim={insurance_company}, CSV={csv_insurance}")
    else:
        print(f"   ❌ Patient not found in CSV database")
    
    # Determine which API to use based on insurance company
    api_url = get_api_url_for_insurer(insurance_company)
    print(f"\n🌐 CLAIM SUBMISSION:")
    print(f"   Target API: {api_url}")
    print(f"   Insurance endpoint: {insurance_company}")
    
    # Prepare API payload with all required fields, handling None values
    api_payload = {
        "patient_id": claim_payload.get("patient_id") or "UNKNOWN",
        "patient_name": claim_payload.get("patient_name") or "Unknown Patient",
        "diagnosis": claim_payload.get("diagnosis") or "General examination",
        "icd_code": claim_payload.get("icd_code") or "Z00.00",  # Default ICD code
        "cpt_code": claim_payload.get("cpt_code") or claim_payload.get("procedure_code") or "99213",
        "claim_amount": float(claim_payload.get("claim_amount") or claim_payload.get("amount") or 0),
        "insurance_company": insurance_company or "Unknown",
        "prior_auth": claim_payload.get("prior_auth") or "Not provided",
        "medical_history": claim_payload.get("medical_history") or "No history available",
        "provider_npi": claim_payload.get("provider_npi") or "1234567890",
        "treatment_date": claim_payload.get("treatment_date") or claim_payload.get("service_date") or claim_payload.get("date") or "2024-01-01"
    }
    
    print(f"📦 API Payload prepared with {len(api_payload)} fields")
    print(f"   🔍 Payload validation:")
    for key, value in api_payload.items():
        print(f"      {key}: {repr(value)}")
    
    try:
        print(f"   📤 Submitting claim to live API...")
        
        # Submit claim with timeout
        async with httpx.AsyncClient(timeout=Settings.TIMEOUT) as client:
            response = await client.post(
                f"{api_url}/submit",
                json=api_payload
            )
            response.raise_for_status()
            result = response.json()
            
            print(f"   ✅ Live API submission successful")
            print(f"      Response status: {result.get('status', 'unknown')}")
        
        # If claim is pending, wait for final result
        if result.get("status") == "pending":
            print(f"   ⏳ Claim processing in progress...")
            state["log"].append(f"[ClaimSubmitter-MCP] Claim submitted, waiting for processing...")
            
            # Wait for processing (simulate real-world delay)
            final_result = await wait_for_claim_processing(api_url, result.get("claim_id"))
            
            if final_result:
                result = final_result
                print(f"   ✅ Processing complete")
                print(f"      Final status: {result.get('status', 'unknown')}")
                if result.get("approved_amount"):
                    print(f"      Approved amount: ${result.get('approved_amount', 0):.2f}")
            else:
                print(f"   ⏱️  Processing timeout occurred")
                print(f"   🔄 Falling back to mock response due to timeout...")
                
                # FIXED: Use mock response instead of timeout to ensure proper rejection flow
                result = generate_mock_submission_result(claim_id, insurance_company, claim_payload)
                
                if result.get("status") == "rejected":
                    print(f"      ❌ Mock rejection (timeout fallback)")
                    print(f"      📝 Reason: {result.get('denial_info', {}).get('reason', 'Timeout during processing')}")
                else:
                    print(f"      ✅ Mock approval (timeout fallback)")
        
    except httpx.ConnectError:
        print(f"   ⚠️  API server not available at {api_url}")
        print(f"   🔄 Using intelligent mock response system...")
        
        # Generate realistic mock response based on claim quality
        result = generate_mock_submission_result(claim_id, insurance_company, claim_payload)
        
        # Enhanced mock response messaging
        if result.get("status") == "approved":
            print(f"      ✅ Mock approval (realistic simulation)")
            print(f"      📊 Data quality: {result.get('data_quality_score', 0)}%")
            print(f"      💰 Amount: ${result.get('approved_amount', 0):.2f}")
        else:
            print(f"      ❌ Mock denial (realistic simulation)")
            print(f"      📝 Reason: {result.get('reason', 'Unknown')}")
        
    except httpx.RequestError as e:
        print(f"   ❌ Network error during submission: {str(e)}")
        print(f"   🔄 Falling back to mock response system...")
        
        result = generate_mock_submission_result(claim_id, insurance_company, claim_payload)
        print(f"      📊 Mock status: {result.get('status', 'unknown')}")
        
    except Exception as e:
        print(f"   ❌ Submission error: {str(e)}")
        print(f"   🔄 Emergency fallback to mock response...")
        
        result = {
            "status": "error", 
            "reason": f"Submission error: {str(e)}",
            "claim_id": claim_id,
            "timestamp": datetime.now().isoformat()
        }
    
    # Store submission result in state
    state["submission_result"] = result
    
    # Set final processing status
    if result.get("status") == "approved":
        state["final_status"] = "approved"
    elif result.get("status") == "denied":
        state["final_status"] = "denied"
    else:
        state["final_status"] = "submission_error"
    
    print(f"\n📊 SUBMISSION SUMMARY:")
    print(f"   Claim ID: {claim_id}")
    print(f"   Final Status: {result.get('status', 'unknown').upper()}")
    
    if result.get("status") == "approved":
        print(f"   Approved Amount: ${result.get('approved_amount', 0)}")
        print(f"   Reference Number: {result.get('reference_number', 'N/A')}")
    elif result.get("status") == "denied":
        print(f"   Denial Reason: {result.get('reason', 'Unknown')}")
        print(f"   Appeal Available: {result.get('appeal_available', 'Unknown')}")
    elif result.get("status") == "error":
        print(f"   Error Details: {result.get('reason', 'Unknown error')}")
    
    # Enhanced logging
    log_entry = (
        f"[ClaimSubmitter-MCP] Status: {result.get('status', 'unknown')}, "
        f"Amount: ${result.get('approved_amount', claim_payload.get('claim_amount', 0))}, "
        f"API: {api_url}, "
        f"Final Status: {state.get('final_status', 'processing')}"
    )
    state["log"].append(log_entry)
    
    secure_log("ClaimSubmitter-MCP", {
        "claim_id": claim_id,
        "patient_id": patient_id,
        "insurance_company": insurance_company,
        "submission_result": result,
        "api_url": api_url,
        "remaining_issues": remaining_issues,
        "csv_data_available": patient_csv_data is not None,
        "eligibility_checked": True,
        "final_status": state.get("final_status", "processing"),
        "log": state.get("log", [])
    })
    
    print("="*80)
    return state


async def wait_for_claim_processing(api_url: str, claim_id: str, max_retries: int = 5) -> dict:
    """Wait for claim processing to complete with retry logic"""
    
    for attempt in range(max_retries):
        try:
            async with httpx.AsyncClient(timeout=10) as client:
                response = await client.get(f"{api_url}/status/{claim_id}")
                response.raise_for_status()
                status_result = response.json()
                
                # Return if processing is complete
                if status_result.get("status") in ["approved", "denied", "processed"]:
                    return status_result
                
                # Wait before next check
                await asyncio.sleep(2)
                
        except Exception as e:
            if attempt == max_retries - 1:
                return None
            await asyncio.sleep(1)
    
    return None


def get_api_url_for_insurer(insurance_company: str) -> str:
    """Route to appropriate API based on insurance company"""
    
    # Primary API: BlueCross, Aetna
    if insurance_company.lower() in ["bluecross", "aetna"]:
        return Settings.PRIMARY_API_URL
    
    # Secondary API: Cigna, United  
    elif insurance_company.lower() in ["cigna", "united"]:
        return Settings.SECONDARY_API_URL
    
    # Default to primary API
    else:
        return Settings.PRIMARY_API_URL

def get_api_url_for_insurer(insurance_company: str) -> str:
    """Route to appropriate API based on insurance company"""
    
    # Primary API: BlueCross, Aetna
    if insurance_company.lower() in ["bluecross", "aetna"]:
        return Settings.PRIMARY_API_URL
    
    # Secondary API: Cigna, United  
    elif insurance_company.lower() in ["cigna", "united"]:
        return Settings.SECONDARY_API_URL
    
    # Default to primary API
    else:
        return Settings.PRIMARY_API_URL

async def wait_for_claim_processing(api_url: str, claim_id: str, max_wait: int = 15) -> dict:
    """Wait for claim processing to complete with shorter timeout"""
    
    start_time = datetime.now()
    attempts = 0
    max_attempts = 3
    
    print(f"   ⏳ Waiting for processing (max {max_wait}s)...")
    
    while (datetime.now() - start_time).seconds < max_wait and attempts < max_attempts:
        try:
            attempts += 1
            print(f"      🔍 Checking status (attempt {attempts}/{max_attempts})...")
            
            async with httpx.AsyncClient(timeout=5) as client:
                response = await client.get(f"{api_url}/claim-status/{claim_id}")
                response.raise_for_status()
                status_result = response.json()
                
                status = status_result.get("status", "unknown")
                print(f"      📊 Current status: {status}")
                
                # Check if processing is complete
                if status in ["approved", "denied"]:
                    print(f"      ✅ Processing complete: {status}")
                    return status_result
                elif status == "processing":
                    print(f"      ⏳ Still processing, waiting...")
                
                # Wait before checking again (shorter interval)
                await asyncio.sleep(3)
                
        except Exception as e:
            print(f"      ⚠️  Error checking status: {str(e)[:50]}...")
            await asyncio.sleep(2)
    
    print(f"   ⏱️  Processing timeout after {max_wait}s")
    return None  # Timeout
